spring:
  # mysql配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://10.62.0.93:3306/E4J
    druid:
      username: root
      password: Cuit2022
    driver-class-name: com.mysql.cj.jdbc.Driver

